# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hackchallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for L7
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SwiftyJSON'

end
